eureka:
  client:
    serviceUrl:
      defaultZone: http://47.95.123.48:8761/eureka/
server:
  port: 8762
spring:
  output:
    ansi:
      enabled: always
  application:
    name: auto-test-backend
  cloud:
    config:
      label: master
      profile: dev
      uri: http:localhost:8888/
  datasource:
      name: auto-test-datasource
      url: jdbc:mysql://47.95.123.48:3306/auto_test?useSSL=false
      username: root
      password: gaoyang
      driver-class-name: com.mysql.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auto.test.group
mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-locations: classpath:mybatis-config.xml